version: '3'
services:
  wcwm_app:
    build: .
    ports:
      - 8080:8080
    environment:
      - WCWM_DB=jdbc:postgresql://wcwm_db:5432/wcwm
    depends_on:
      - wcwm_db
  wcwm_db:
    image: postgres:10
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=wcwm
