version: '3'
services:
  wcwm_app:
    build: .
    ports:
      - 8080:8080
    environment:
      - WCWM_ENCRYPTION_KEY=hehe123
      - WCWM_PORT=8080
      - WCWM_CORS=*
      - WCWM_DB_PASSWORD=root
      - WCWM_DB_USERNAME=postgres
      - WCWM_DB_URI=jdbc:postgresql://wcwm_db:5432/wcwm
    depends_on:
      - wcwm_db
  wcwm_db:
    image: postgres:10
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=wcwm
