apiVersion: v1
kind: PersistentVolume
metadata:
  name: psql-pv
  labels:
    type: local
spec:
  storageClassName: standard
  capacity:
    storage: 250Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: psql-pv-claim
  labels:
    app: wcwm-app
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 250Mi
---
apiVersion: v1
kind: Service
metadata:
  name: wcwm-app-psql
  labels:
    app: wcwm-app
spec:
  ports:
    - port: 5432
  selector:
    app: wcwm-app
    tier: psql
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wcwm-app-psql
  labels:
    app: wcwm-app
spec:
  selector:
    matchLabels:
      app: wcwm-app
      tier: psql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wcwm-app
        tier: psql
    spec:
      containers:
        - image: postgres:10
          name: psql
          env:
            - name: POSTGRES_PASSWORD
              value: root
            - name: POSTGRES_DB
              value: wcwm
          ports:
            - containerPort: 5432
              name: psql
          volumeMounts:
            - name: psql-persistent-storage  # This name should match the name specified in `volumes.name`
              mountPath: /var/lib/psql
      volumes:                       # A PersistentVolume is mounted as a volume to the Pod
        - name: psql-persistent-storage
          persistentVolumeClaim:
            claimName: psql-pv-claim