---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wcwm-app-server
  labels:
    app: wcwm-app-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wcwm-app-server
  template:
    metadata:
      labels:
        app: wcwm-app-server
    spec:
      containers:
        - name: wcwm-app-server
          image: mtesluk/wcwm
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
          resources:
            limits:
              cpu: 0.2
              memory: "200Mi"
          env:
            - name: WCWM_DB
              value: "jdbc:postgresql://wcwm-app-psql:5432/wcwm"
---
apiVersion: v1
kind: Service
metadata:
  name: wcwm-app-server
  labels:
    app: wcwm-app-server
spec:
  type: NodePort
  selector:
    app: wcwm-app-server
  ports:
    - name: http
      port: 8080
      targetPort: 8080